try{

}catch(error){
    console.log(`Aviso !\nErro: ${error}`)
}